catalogo = {
    "0001": {"nome": "Matrix", "ano": 1999, "genero": "Ficção", "disponibilidade": "disponível", "diretor": "Lana Wachowski, Lilly Wachowski", "empresa produtora": "Warner Bros.", "avaliação": 87},
    "0002": {"nome": "Titanic", "ano": 1997, "genero": "Romance", "disponibilidade": "disponível", "diretor": "James Cameron", "empresa produtora": "Paramount Pictures", "avaliação": 89},
    "0003": {"nome": "Vingadores", "ano": 2012, "genero": "Ação", "disponibilidade": "disponível", "diretor": "Joss Whedon", "empresa produtora": "Marvel Studios", "avaliação": 91},
    "0004": {"nome": "Shrek", "ano": 2001, "genero": "Animação", "disponibilidade": "disponível", "diretor": "Andrew Adamson, Vicky Jenson", "empresa produtora": "DreamWorks Animation", "avaliação": 88},
    "0005": {"nome": "Coringa", "ano": 2019, "genero": "Drama", "disponibilidade": "disponível", "diretor": "Todd Phillips", "empresa produtora": "Warner Bros.", "avaliação": 68},
    "0006": {"nome": "Interestelar", "ano": 2014, "genero": "Ficção", "disponibilidade": "disponível", "diretor": "Christopher Nolan", "empresa produtora": "Paramount Pictures", "avaliação": 86},
    "0007": {"nome": "O Senhor dos Anéis", "ano": 2001, "genero": "Fantasia", "disponibilidade": "disponível", "diretor": "Peter Jackson", "empresa produtora": "New Line Cinema", "avaliação": 91},
    "0008": {"nome": "Harry Potter", "ano": 2001, "genero": "Fantasia", "disponibilidade": "disponível", "diretor": "Chris Columbus", "empresa produtora": "Warner Bros.", "avaliação": 81},
    "0009": {"nome": "Star Wars", "ano": 1977, "genero": "Ficção", "disponibilidade": "disponível", "diretor": "George Lucas", "empresa produtora": "Lucasfilm", "avaliação": 92},
    "0010": {"nome": "Jurassic Park", "ano": 1993, "genero": "Aventura", "disponibilidade": "disponível", "diretor": "Steven Spielberg", "empresa produtora": "Universal Pictures", "avaliação": 91},
    "0011": {"nome": "O Poderoso Chefão", "ano": 1972, "genero": "Crime", "disponibilidade": "disponível", "diretor": "Francis Ford Coppola", "empresa produtora": "Paramount Pictures", "avaliação": 98},
    "0012": {"nome": "Casablanca", "ano": 1942, "genero": "Romance", "disponibilidade": "disponível", "diretor": "Michael Curtiz", "empresa produtora": "Warner Bros.", "avaliação": 97},
    "0013": {"nome": "O Senhor dos Anéis: As Duas Torres", "ano": 2002, "genero": "Fantasia", "disponibilidade": "disponível", "diretor": "Peter Jackson", "empresa produtora": "New Line Cinema", "avaliação": 95},
    "0014": {"nome": "O Senhor dos Anéis: O Retorno do Rei", "ano": 2003, "genero": "Fantasia", "disponibilidade": "disponível", "diretor": "Peter Jackson", "empresa produtora": "New Line Cinema", "avaliação": 93},
    "0015": {"nome": "O Grande Lebowski", "ano": 1998, "genero": "Comédia", "disponibilidade": "disponível", "diretor": "Joel Coen, Ethan Coen", "empresa produtora": "PolyGram Filmed Entertainment", "avaliação": 83},
    "0016": {"nome": "Pulp Fiction", "ano": 1994, "genero": "Crime", "disponibilidade": "disponível", "diretor": "Quentin Tarantino", "empresa produtora": "Miramax Films", "avaliação": 92},
    "0017": {"nome": "O Rei Leão", "ano": 1994, "genero": "Animação", "disponibilidade": "disponível", "diretor": "Roger Allers, Rob Minkoff", "empresa produtora": "Walt Disney Feature Animation", "avaliação": 93},
    "0018": {"nome": "Forrest Gump", "ano": 1994, "genero": "Drama", "disponibilidade": "disponível", "diretor": "Robert Zemeckis", "empresa produtora": "Paramount Pictures", "avaliação": 71},
    "0019": {"nome": "O Silêncio dos Inocentes", "ano": 1991, "genero": "Terror", "disponibilidade": "disponível", "diretor": "Jonathan Demme", "empresa produtora": "Orion Pictures", "avaliação": 96},
    "0020": {"nome": "Clube da Luta", "ano": 1999, "genero": "Drama", "disponibilidade": "disponível", "diretor": "David Fincher", "empresa produtora": "20th Century Fox", "avaliação": 79},
    "0021": {"nome": "O Exorcista", "ano": 1973, "genero": "Terror", "disponibilidade": "disponível", "diretor": "William Friedkin", "empresa produtora": "Warner Bros.", "avaliação": 84},
    "0022": {"nome": "O Iluminado", "ano": 1980, "genero": "Terror", "disponibilidade": "disponível", "diretor": "Stanley Kubrick", "empresa produtora": "Warner Bros.", "avaliação": 93},
    "0023": {"nome": "O Labirinto do Fauno", "ano": 2006, "genero": "Fantasia", "disponibilidade": "disponível", "diretor": "Guillermo del Toro", "empresa produtora": "Warner Bros.", "avaliação": 95},
    "0024": {"nome": "O Pianista", "ano": 2002, "genero": "Drama", "disponibilidade": "disponível", "diretor": "Roman Polanski", "empresa produtora": "Canal+", "avaliação": 85},
    "0025": {"nome": "O Cavaleiro das Trevas", "ano": 2008, "genero": "Ação", "disponibilidade": "disponível", "diretor": "Christopher Nolan", "empresa produtora": "Warner Bros.", "avaliação": 94},
    "0026": {"nome": "A Origem", "ano": 2010, "genero": "Ficção", "disponibilidade": "disponível", "diretor": "Christopher Nolan", "empresa produtora": "Warner Bros.", "avaliação": 86},
    "0027": {"nome": "O Lobo de Wall Street", "ano": 2013, "genero": "Comédia", "disponibilidade": "disponível", "diretor": "Martin Scorsese", "empresa produtora": "Paramount Pictures", "avaliação": 79},
    "0028": {"nome": "A Lista de Schindler", "ano": 1993, "genero": "Drama", "disponibilidade": "disponível", "diretor": "Steven Spielberg", "empresa produtora": "Universal Pictures", "avaliação": 93},
    "0029": {"nome": "O Poderoso Chefão: Parte II", "ano": 1974, "genero": "Crime", "disponibilidade": "disponível", "diretor": "Francis Ford Coppola", "empresa produtora": "Paramount Pictures", "avaliação": 97},
    "0030": {"nome": "O Poderoso Chefão: Parte III", "ano": 1990, "genero": "Crime", "disponibilidade": "disponível", "diretor": "Francis Ford Coppola", "empresa produtora": "Paramount Pictures", "avaliação": 68},
    "0031": {"nome": "O Grande Hotel Budapeste", "ano": 2014, "genero": "Comédia", "disponibilidade": "disponível", "diretor": "Wes Anderson", "empresa produtora": "Fox Searchlight Pictures", "avaliação": 91},
    "0032": {"nome": "O Menino do Pijama Listrado", "ano": 2008, "genero": "Drama", "disponibilidade": "disponível", "diretor": "Mark Herman", "empresa produtora": "Miramax Films", "avaliação": 74},
    "0033": {"nome": "O Regresso", "ano": 2015, "genero": "Aventura", "disponibilidade": "disponível", "diretor": "Alejandro González Iñárritu", "empresa produtora": "20th Century Fox", "avaliação": 78},
    "0034": {"nome": "O Discurso do Rei", "ano": 2010, "genero": "Drama", "disponibilidade": "disponível", "diretor": "Tom Hooper", "empresa produtora": "The Weinstein Company", "avaliação": 86},
    "0035": {"nome": "O Labirinto de Pan", "ano": 2006, "genero": "Fantasia", "disponibilidade": "disponível", "diretor": "Guillermo del Toro", "empresa produtora": "Warner Bros.", "avaliação": 95},
    "0036": {"nome": "O Grande Truque", "ano": 2006, "genero": "Mistério", "disponibilidade": "disponível", "diretor": "Christopher Nolan", "empresa produtora": "Warner Bros.", "avaliação": 92},
    "0037": {"nome": "O Quarto de Jack", "ano": 2015, "genero": "Drama", "disponibilidade": "disponível", "diretor": "Lenny Abrahamson", "empresa produtora": "Element Pictures", "avaliação": 93}
}